### ISSUE TITLE
Could you add onFinishedUpload callback?

### ISSUE THREAD

**Issue by karol-unum-la** [uploadcare/blocks#220]
@nd0ut I would like to get an uploaded image's url when upload process is finished

I am looking for something like this:

```
      <lr-file-uploader-inline ref={ref} class={classNames}>
        <lr-upload-ctx-provider ref={widgetContext}></lr-upload-ctx-provider>
      </lr-file-uploader-inline>

...

widgetContext.current.setOnUploadFinished((uploadedFileUrls) => {
// some react state changes from my app
})

```

**Comment by nd0ut** [comment]
Hey @karol-unum-la,

we're workin on that in https://github.com/uploadcare/uc-blocks/pull/226/
you'll be able to catch `uploading finished` event from the `lr-data-output` block

**Comment by nd0ut** [comment]
Hey @karol-unum-la,

see https://uploadcare.github.io/blocks/docs/events/
