### ISSUE TITLE
Cloud Image Editor docs erring on page load.

### ISSUE THREAD

**Issue by jeffreytgilbert** [uploadcare/blocks#397]
Errors appear in the console and the editor does not display for the Cloud Image Editor in the documentation.

Page: https://uploadcare.github.io/blocks/blocks/CloudImageEditor/

Browser is Safari. Issue is reproducible on multiple refreshes. Chrome also errors, though says something different.

In Safari:

[Error] TypeError: Module specifier, '@symbiotejs/symbiote' does not start with "/", "./", or "../". Referenced from https://uploadcare.github.io/blocks/abstract/Block.js [Error] TypeError: Module specifier, '@symbiotejs/symbiote' does not start with "/", "./", or "../". Referenced from https://uploadcare.github.io/blocks/index.js (x2) [Error] TypeError: Module specifier, '@symbiotejs/symbiote' does not start with "/", "./", or "../". Referenced from https://uploadcare.github.io/blocks/index.js (x2) [Error] Unhandled Promise Rejection: Error: [cloud-image-editor] timout waiting for non-zero container size (anonymous function) (d1162f6b-9517-44ba-b816-f56e87049bcc:77) asyncFunctionResume (anonymous function) promiseReactionJobWithoutPromise promiseReactionJob [Error] Unhandled Promise Rejection: Error: [cloud-image-editor] timout waiting for non-zero container size (anonymous function) (435f80c4-f474-4d6f-888f-9ed480692423:77) asyncFunctionResume (anonymous function) promiseReactionJobWithoutPromise promiseReactionJob

In Chrome:

CloudEditor.js:56 Uncaught (in promise) Error: [cloud-image-editor] timout waiting for non-zero container size at callback (CloudEditor.js:56:18)

**Comment by nd0ut** [comment]
Hey @jeffreytgilbert, 

There was a problem with the container size in which the cloud editor was being rendered. I fixed it, thank you for attention!
